import {useEffect,useState} from 'react';
import {validSubmissionSource} from '../lib/submissions.js';
import * as api from '../lib/api';
export function SubmissionList({admin=false}){
 const [tab,setTab]=useState('pending'),[saving,setSaving]=useState('');
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[image,setImage]=useState('');
 useEffect(()=>{let alive=true;api.getSubmissions().then(data=>{if(alive)setRows(data)}).catch(()=>{if(alive)setError('제보함을 불러오지 못했습니다. 제출 기능 DB 설정을 확인해주세요.')});return()=>{alive=false}},[]);
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image)},[image]);
 return <div className="panel form-stack"><h2>{admin?'회원 시간표 제보함':'내 제출 내역'}</h2>{error&&<p className="error">{error}</p>}{!error&&!rows.length&&<p className="helper">아직 제출 내역이 없습니다.</p>}{admin&&<div className="admin-toolbar">{[['pending','검수 대기'],['completed','검수 완료']].map(([value,label])=><button className={tab===value?'primary':'secondary'} aria-pressed={tab===value} key={value} onClick={()=>setTab(value)}>{label} ({rows.filter(r=>r.status===value).length})</button>)}</div>}{admin&&rows.length>0&&!rows.some(r=>r.status===tab)&&<p className="helper">이 상태의 제보가 없습니다.</p>}{rows.filter(row=>!admin||row.status===tab).map(row=><article className="submission-card" key={row.id}><div className="submission-heading"><h3>{row.title}</h3><span className="helper">{row.status==='completed'?'✓ 검수 완료':'검수 대기'}</span></div>{validSubmissionSource(row.source_url)?<a className="submission-source" href={row.source_url} target="_blank" rel="noopener noreferrer">출처 링크 열기 ↗<span>{row.source_url}</span></a>:<p className="helper">출처 링크 없음 (기존 제보)</p>}<p className="helper">{new Date(row.created_at).toLocaleString('ko-KR')}{` · 제보자 ${row.nickname||'닉네임 미설정'}`}</p>{admin&&<label className="checkbox-label"><input type="checkbox" checked={row.status==='completed'} disabled={Boolean(saving)} onChange={async e=>{const status=e.target.checked?'completed':'pending';setSaving(row.id);setError('');try{const updated=await api.setSubmissionStatus(row,status);setRows(current=>current.map(item=>item.id===row.id?{...item,...updated}:item));}catch(e){setError(e.message)}finally{setSaving('')}}}/>검수 완료{saving===row.id?' · 저장 중…':''}</label>}{row.reviewed_at&&<p className="helper">검수 완료일 · {new Date(row.reviewed_at).toLocaleString('ko-KR')}</p>}{!row.image_paths.length&&<p className="helper">첨부 이미지 없음 · 출처 링크에서 확인해주세요.</p>}{row.image_paths.map((path,i)=><button className="secondary" key={path} onClick={async()=>{try{const blob=await api.submissionImage(path);setImage(URL.createObjectURL(blob))}catch(e){setError(e.message)}}}>첨부 이미지 {i+1}</button>)}</article>)}{image&&<><button className="text-button" onClick={()=>setImage('')}>원본 닫기</button><img src={image} style={{maxWidth:'100%'}} alt="제출된 캐스팅표 원본"/></>}</div>
}
export default function SubmitSchedule({productions,nickname}){
 const [productionId,setProductionId]=useState(''),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(0);
 return <section className="page narrow"><div className="eyebrow">SHARE A SCHEDULE</div><h1>시간표 제출</h1><p className="intro-copy">최신 캐스팅표를 공유해주세요. 관리자 검수 후 공연 일정에 반영됩니다.</p><form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setError('');if(files.length>5||files.some(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>8*1024*1024)){setError('JPG·PNG·WEBP 이미지는 최대 5장, 한 장당 8MB 이하로 올려주세요.');return;}const form=e.currentTarget,data=new FormData(form);const source=String(data.get('source_url')).trim();if(!validSubmissionSource(source)){setError('출처 링크를 입력해주세요. https://로 시작하는 올바른 주소가 필요합니다.');return;}setBusy(true);try{await api.submitSchedule({production_id:productionId,title:productions.find(p=>p.id===productionId)?.title||String(data.get('title')).trim(),source_url:source,files});form.reset();setProductionId('');setFiles([]);setSaved(n=>n+1);}catch(e){setError(e.message)}finally{setBusy(false)}}}><p className="helper">제보자: {nickname} · <a href="#/account">닉네임 변경</a></p><label>공연<select value={productionId} disabled={busy} onChange={e=>setProductionId(e.target.value)}><option value="">목록에 없는 공연</option>{productions.map(p=><option key={p.id} value={p.id}>{p.title} · {p.venue} · {p.start_date.slice(0,4)}</option>)}</select></label>{!productionId&&<label>공연명<input name="title" required maxLength={120} disabled={busy}/></label>}<label>출처 링크 (필수)<input name="source_url" type="url" placeholder="https://" required maxLength={2000} disabled={busy}/><span className="helper">공식 예매처·제작사 등의 캐스팅 일정이 나와 있는 게시물 주소를 입력해주세요.</span></label><label>캐스팅표 이미지 (선택)<input type="file" accept="image/png,image/jpeg,image/webp" multiple disabled={busy} onChange={e=>setFiles([...e.target.files])}/><span className="helper">링크만으로 제출할 수 있어요. 이미지 첨부 시 최대 5장, 한 장당 8MB 이하.</span></label>{error&&<p className="error" role="alert">{error}</p>}{saved>0&&<p role="status">제출했습니다. 아래 내역에서 확인하세요.</p>}<button className="primary" disabled={busy}>{busy?'제출 중…':'검수 요청하기'}</button></form><SubmissionList key={saved}/></section>
}
