import {useEffect,useMemo,useRef,useState} from 'react';
import Icon from './components/Icon';
import SessionCard from './components/SessionCard';
import Admin from './components/Admin';
import {demoProductions,demoSessions} from './lib/demo';
import {filterSessions,actorOptions,sortSessions,classify} from './lib/domain';
import {readLocal,writeLocal} from './lib/storage';
import * as api from './lib/api';
const demo=!api.configured;
const demoKey='castingpick.elisabeth.preview.v1';
function useRoute(){const [route,setRoute]=useState(location.hash.slice(1)||'/');useEffect(()=>{const onHash=()=>{setRoute(location.hash.slice(1)||'/');window.scrollTo({top:0,behavior:'instant'})};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);return route;}
export default function App(){
 const route=useRoute();const [data,setData]=useState(()=>demo?readLocal(demoKey,{productions:demoProductions,sessions:demoSessions}):{productions:[],sessions:[]});
 const [loading,setLoading]=useState(!demo),[error,setError]=useState(''),[user,setUser]=useState(api.getSession()?.user||null),[admin,setAdmin]=useState(false);
 const [favorites,setFavorites]=useState(()=>readLocal('castingpick.favorites.guest',[])),[toast,setToast]=useState('');const toastTimer=useRef(null),savingFavorites=useRef(new Set());
 const {productions,sessions}=data;
 const favoritesRef=useRef(favorites);useEffect(()=>{favoritesRef.current=favorites},[favorites]);
 function notify(text){clearTimeout(toastTimer.current);setToast(text);toastTimer.current=setTimeout(()=>setToast(''),3500)}
 async function reload(){setLoading(true);setError('');try{const [productions,sessions]=await Promise.all([api.getProductions(),api.getPerformances()]);setData({productions,sessions});}catch(e){setError('공연 데이터를 불러오지 못했어요. 연결 설정을 확인하고 다시 시도해주세요.');throw e;}finally{setLoading(false)}}
 useEffect(()=>{if(!demo)reload().catch(()=>{});const auth=()=>setUser(api.getSession()?.user||null);window.addEventListener('castingpick-auth',auth);return()=>{window.removeEventListener('castingpick-auth',auth);clearTimeout(toastTimer.current)}},[]);
 useEffect(()=>{let alive=true;if(!demo&&user){setAdmin(false);Promise.all([api.isAdmin(),api.getFavorites()]).then(([allowed,ids])=>{if(alive){setAdmin(allowed===true);setFavorites(ids)}}).catch(()=>{if(alive)notify('계정 정보를 불러오지 못했어요. 다시 로그인해주세요.')});}else{setAdmin(false);setFavorites(readLocal('castingpick.favorites.guest',[]));}return()=>{alive=false}},[user]);
 async function toggleFavorite(id){if(savingFavorites.current.has(id))return;savingFavorites.current.add(id);const next=!favorites.includes(id);try{if(!demo&&user)await api.saveFavorite(id,next);const ids=next?[...new Set([...favoritesRef.current,id])]:favoritesRef.current.filter(v=>v!==id);if(demo||!user)writeLocal('castingpick.favorites.guest',ids);favoritesRef.current=ids;setFavorites(ids);notify(next?'관심 회차에 저장했어요.':'관심 회차에서 해제했어요.');}catch(e){notify(e.message)}finally{savingFavorites.current.delete(id)}}
 async function saveDemo(productionId,rows,baseline){const result={new:0,changed:0,duplicate:0};const next=[...sessions];for(const row of rows){const status=classify(row,baseline);result[status]++;if(status==='duplicate')continue;const i=next.findIndex(s=>s.production_id===productionId&&s.starts_at===row.starts_at);const updated={...row,id:i<0?crypto.randomUUID():next[i].id,cast:row.cast.map(c=>({...c,actor:c.actor.trim()})),updated_at:new Date().toISOString()};if(i<0)next.push(updated);else next[i]=updated;}const state={productions,sessions:next};writeLocal(demoKey,state);setData(state);return result;}
 async function createProduction(value){const p=demo?{...value,id:crypto.randomUUID(),updated_at:new Date().toISOString()}:await api.addProduction(value);const state={productions:[...productions,p],sessions};if(demo)writeLocal(demoKey,state);setData(state);return p;}
 const id=route.startsWith('/show/')?decodeURIComponent(route.slice(6)):null;
 const selected=productions.find(p=>p.id===id);const isFavorites=route==='/favorites',isAdmin=route==='/admin';
 return <div className="app-shell"><header className="site-header"><a className="brand" href="#/" aria-label="캐스팅픽 공연 목록">캐스팅픽<span>.</span></a><nav className="desktop-nav" aria-label="주요 메뉴"><a href="#/" className={!isFavorites&&!isAdmin?'active':''}>공연 찾기</a><a href="#/favorites" className={isFavorites?'active':''}>관심 회차</a><a href="#/admin" className={isAdmin?'active':''}>캐스팅표 등록</a></nav><div className="header-right">{demo?<span className="demo-label">DEMO</span>:user?<button className="text-button" onClick={()=>api.signOut().catch(e=>notify(e.message))}>로그아웃</button>:<a className="icon-button" href="#/admin" aria-label="관리자 로그인"><Icon name="user"/></a>}<span className="header-flower">✳</span></div></header>
 {demo&&<div className="demo-banner">첨부 스케줄 기반 미리보기입니다. 변경 사항과 관심 회차는 이 기기에만 저장돼요.</div>}
 {api.incompleteConfig&&<div className="error">Supabase URL과 공개 키를 모두 설정해주세요. 현재는 데모로 표시됩니다.</div>}
 <main id="main-content">{loading?<div className="page loading" role="status">공연을 불러오는 중이에요…</div>:error?<div className="page empty" role="alert"><h2>잠시 연결이 끊겼어요</h2><p>{error}</p><button className="primary" onClick={()=>reload().catch(()=>{})}>다시 불러오기</button></div>:isAdmin?<Admin productions={productions} sessions={sessions} demo={demo} user={user} admin={admin} onLogin={api.signIn} onSaved={demo?saveDemo:reload} onCreate={createProduction} notify={notify}/>:isFavorites?<section className="page narrow"><div className="eyebrow">MY PICKS</div><h1>기다려지는 날들<span className="title-dot">.</span></h1><p className="intro-copy">내가 고른 무대, 한곳에 모아두세요.</p><div className="section-line"><h2>관심 회차 <span>{favorites.filter(id=>sessions.some(s=>s.id===id)).length}</span></h2><span className="helper">{user&&!demo?'계정에 저장됨':'이 기기에 저장됨'}</span></div>{sortSessions(sessions.filter(s=>favorites.includes(s.id))).map(s=><SessionCard key={s.id} session={s} production={productions.find(p=>p.id===s.production_id)} favorite onFavorite={toggleFavorite} showTitle/>)}{!sessions.some(s=>favorites.includes(s.id))&&<div className="empty"><Icon name="heart" size={32}/><h2>아직 비어 있는 관극 노트</h2><p>마음에 드는 회차의 하트를 눌러보세요.</p><a className="primary" href="#/">공연 둘러보기</a></div>}</section>:selected?<Detail key={selected.id} production={selected} sessions={sessions.filter(s=>s.production_id===id)} favorites={favorites} onFavorite={toggleFavorite}/>:id?<section className="page empty"><h1>공연을 찾을 수 없어요</h1><a href="#/" className="primary">공연 목록으로</a></section>:<Home productions={productions}/> }</main>
 <footer className="site-footer"><span className="brand small">캐스팅픽.</span><span>보고 싶은 배우, 볼 수 있는 날.</span></footer><nav className="mobile-nav" aria-label="모바일 메뉴"><a href="#/" aria-current={!isFavorites&&!isAdmin?'page':undefined}><Icon name="ticket"/><span>공연 찾기</span></a><a href="#/favorites" aria-current={isFavorites?'page':undefined}><Icon name="heart"/><span>관심 회차</span></a><a href="#/admin" aria-current={isAdmin?'page':undefined}><Icon name="upload"/><span>시간표 등록</span></a></nav>{toast&&<div className="toast" role="status">{toast}</div>}</div>
}
function Home({productions}){const [query,setQuery]=useState('');const results=productions.filter(p=>`${p.title} ${p.venue}`.includes(query.trim()));return <section className="page home-page"><div className="home-hero"><div><div className="eyebrow">A LITTLE PICK, A SPECIAL NIGHT</div><h1>보고 싶은 배우,<br/>볼 수 있는 날<span className="title-dot">.</span></h1><p>나만의 캐스팅으로 찾는<br className="mobile-only"/> 다음 관극의 순간.</p></div><div className="hero-ticket" aria-hidden="true"><span>YOUR NEXT</span><strong>뮤지컬의<br/>한 장면</strong><div className="ticket-star">✳</div><span>CASTING PICK — 2026</span></div></div><label className="search-field"><Icon name="search"/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="어떤 공연을 찾고 있나요?" aria-label="공연명 또는 공연장 검색"/><kbd>검색</kbd></label><div className="section-line"><h2>{query?'검색 결과':'공연 둘러보기'} <span>{results.length}</span></h2><span className="helper">작품을 골라 시작하세요</span></div><div className="production-grid">{results.map((p,i)=><a className="production-card" key={p.id} href={`#/show/${p.id}`}>{p.poster_url?<img className="poster-image" src={p.poster_url} alt={`${p.title} 공식 포스터`} loading="lazy"/>:(<div className={`poster motif-${p.motif||'moon'}`} aria-hidden="true"><span className="poster-label">MUSICAL · {p.start_date.slice(0,4)}</span><span className="poster-shape"/><div className="poster-title">{p.title.split(' ').map((word,j)=><span key={j}>{word}</span>)}</div><span className="poster-subtitle">{p.subtitle||'무대 위에서 만나는 특별한 순간'}</span><span className="poster-bottom">CASTING PICK COLLECTION　0{i+1}</span></div>)}<div className="production-info"><div><h3>{p.title}</h3><p>{p.venue}</p><span>{p.start_date.replaceAll('-','.')} — {p.end_date.slice(5).replace('-','.')}</span></div><span className="card-arrow"><Icon name="arrow" size={18}/></span></div></a>)}</div>{!results.length&&<div className="empty"><Icon name="search" size={30}/><h2>{query?'검색 결과가 없어요':'등록된 공연이 없어요'}</h2><p>{query?'공연명이나 공연장을 다시 확인해주세요.':'관리자 화면에서 첫 공연을 등록해주세요.'}</p></div>}</section>}
function Detail({production,sessions,favorites,onFavorite}){
 const [actors,setActors]=useState({}),[from,setFrom]=useState(''),[to,setTo]=useState(''),[weekends,setWeekends]=useState(false);
 const filterRoles=production.filter_roles??production.roles;
 const options=useMemo(()=>actorOptions(sessions,production.roles),[sessions,production.roles]);
 const invalid=Boolean(from&&to&&from>to);const filtered=invalid?[]:filterSessions(sessions,{actors,from,to,weekends});const count=Object.values(actors).reduce((n,a)=>n+a.length,0);
 function toggle(role,name){setActors(old=>({...old,[role]:old[role]?.includes(name)?old[role].filter(n=>n!==name):[...(old[role]||[]),name]}))}
 function reset(){setActors({});setFrom('');setTo('');setWeekends(false)}
 return <section className="page detail-page"><a className="back-link" href="#/"><Icon name="back" size={16}/>공연 목록</a><div className="detail-intro"><div><div className="eyebrow">MUSICAL · {production.start_date.slice(0,4)}</div><h1>{production.title}<span className="title-dot">.</span></h1><p className="show-meta">{production.venue}<span>·</span>{production.start_date.replaceAll('-','.')} — {production.end_date.slice(5).replace('-','.')}</p></div>{production.poster_url?<img className="detail-poster" src={production.poster_url} alt={`${production.title} 공식 포스터`}/>:<div className="detail-symbol" aria-hidden="true">✳</div>}</div><div className="detail-layout"><aside className="filter-panel"><div className="filter-title"><h2>보고 싶은 배우를 골라요</h2><button className="text-button" onClick={reset}>초기화</button></div>{filterRoles.map(role=><fieldset className="role-filter" key={role}><legend>{role} 역</legend><div className="actor-chips">{options[role].map(name=><button key={name} aria-pressed={actors[role]?.includes(name)||false} className="actor-chip" onClick={()=>toggle(role,name)}><Icon name={actors[role]?.includes(name)?'check':'plus'} size={13}/>{name}</button>)}{!options[role].length&&<span className="helper">등록된 출연진이 없어요</span>}</div></fieldset>)}<p className="filter-help">같은 역할은 선택한 배우 중 한 명,<br/>다른 역할은 함께 출연하는 회차를 찾아요.</p><div className="date-filter"><div className="filter-title"><h2><Icon name="calendar" size={16}/>볼 수 있는 날짜</h2></div><div className="two-columns"><label>시작일<input aria-label="시작일" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>종료일<input aria-label="종료일" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><label className="checkbox-label"><input type="checkbox" checked={weekends} onChange={e=>setWeekends(e.target.checked)}/>주말만 보기</label>{invalid&&<p className="error" role="alert">종료일은 시작일 이후로 선택해주세요.</p>}</div></aside><div className="results-panel"><div className="section-line result-heading"><h2 aria-live="polite">{count||from||to||weekends?'조건에 맞는 회차':'전체 회차'} <span>{filtered.length}</span></h2><span className="helper">날짜순</span></div>{count>0&&<div className="selected-summary"><span className="selection-dot"/>{Object.values(actors).flat().join(' · ')}</div>}{filtered.map(s=><SessionCard key={s.id} session={s} production={production} actors={actors} favorite={favorites.includes(s.id)} onFavorite={onFavorite}/>)}{!filtered.length&&<div className="empty"><Icon name="calendar" size={28}/><h2>조건에 맞는 회차가 없어요</h2><p>배우나 날짜를 바꿔 다시 찾아보세요.</p><button className="secondary" onClick={reset}>필터 초기화</button></div>}<p className="results-note">캐스팅은 변경될 수 있어요.<br/>예매 전 공식 공지를 한 번 더 확인해주세요.</p></div></div></section>
}
